language: cpp
dist: focal

addons:
  apt:
    packages:
      - arduino
      - arduino-mk
      - python3
      - python3-pip
      - xvfb   # Add xvfb to handle headless mode

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3-serial

install:
  - pip3 install pyserial

script:
  # Add your Arduino setup commands here
  - export ARDUINO_DIR=/usr/share/arduino
  - export PATH=$ARDUINO_DIR:$PATH
  - export BOARDS="arduino:avr:uno arduino:avr:mega arduino:samd:mkr1000" # List your boards here

  # Compile the library for each board using xvfb-run
  - |
    for BOARD in $BOARDS; do
      echo "Compiling for $BOARD"
      xvfb-run arduino --verify --board $BOARD --pref build.path=build-$BOARD examples/BasicExample/BasicExample.ino
    done

  # Run tests by uploading the sketch and checking the serial output using xvfb-run
  - |
    for BOARD in $BOARDS; do
      echo "Running tests on $BOARD"
      xvfb-run arduino --upload --board $BOARD --pref build.path=build-$BOARD examples/BasicExample/BasicExample.ino
      python3 validate_serial_output.py /dev/ttyUSB0
    done