#!/usr/bin/env python3
"""Generate example terminal screenshots from ANSI scenario fixtures."""

from __future__ import annotations

import argparse
import hashlib
import random
import shutil
import sys
import tempfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from render import render_gif, render_png  # noqa: E402
from scenarios import SCENARIOS  # noqa: E402

ROSTER_PATH = ROOT / "docs" / "screenshots" / "roster.yml"
DEFAULT_OUT = ROOT / "docs" / "screenshots"
SEED = 0xA75E2026


def load_roster() -> dict:
    with ROSTER_PATH.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def file_digest(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def zlib_crc(s: str) -> int:
    h = 0
    for ch in s.encode():
        h = (h * 33 + ch) & 0xFFFFFFFF
    return h


def build_index_md(roster: dict) -> str:
    lines = [
        "# Screenshot index",
        "",
        "Generated by `tools/screenshots/generate.py`. Do not edit by hand.",
        "",
        "## Heroes (README)",
        "",
        "| Anchor | File | Caption |",
        "|--------|------|---------|",
    ]
    for h in roster.get("heroes", []):
        lines.append(
            f"| `#{h['readme_anchor']}` | `{h['file']}` | {h['caption']} |"
        )
    lines += [
        "",
        "## Examples (Wiki)",
        "",
        "| ID | Example | Static | Motion | Wiki |",
        "|----|---------|--------|--------|------|",
    ]
    for e in roster["examples"]:
        motion = e.get("motion", "—")
        lines.append(
            f"| `{e['id']}` | {e['example']} | `{e['static']}` | `{motion}` | "
            f"[{e['wiki_page']}](https://github.com/NicholasTracy/ANSITerm/wiki/{e['wiki_page']}#{e['wiki_anchor']}) |"
        )
    lines.append("")
    return "\n".join(lines)


def generate_all(seed: int, out_dir: Path) -> list[Path]:
    roster = load_roster()
    written: list[Path] = []
    out_dir.mkdir(parents=True, exist_ok=True)

    for entry in roster["examples"]:
        eid = entry["id"]
        if eid not in SCENARIOS:
            raise SystemExit(f"No scenario for id={eid}")
        sc = SCENARIOS[eid]
        cols, rows = sc["cols"], sc["rows"]
        rng = random.Random(seed ^ zlib_crc(eid))

        static_path = out_dir / entry["static"]
        render_png(sc["static"](rng), cols, rows, static_path)
        written.append(static_path)

        if entry.get("motion"):
            rng_m = random.Random(seed ^ zlib_crc(eid + "-motion"))
            frames = sc["motion"](rng_m)
            motion_path = out_dir / entry["motion"]
            render_gif(frames, cols, rows, motion_path, duration_ms=140)
            written.append(motion_path)

    for hero in roster.get("heroes", []):
        eid = hero["id"]
        sc = SCENARIOS[eid]
        rng = random.Random(seed ^ zlib_crc(eid + "-hero"))
        path = out_dir / hero["file"]
        render_png(sc["static"](rng), sc["cols"], sc["rows"], path)
        written.append(path)

    # Keep roster.yml in place; write generated index
    if out_dir.resolve() == DEFAULT_OUT.resolve():
        # Copy roster is already there
        pass
    else:
        shutil.copy2(ROSTER_PATH, out_dir / "roster.yml")

    index_path = out_dir / "index.md"
    index_path.write_text(build_index_md(roster), encoding="utf-8")
    written.append(index_path)
    return written


def expected_paths(out_dir: Path) -> list[Path]:
    roster = load_roster()
    paths: list[Path] = []
    for e in roster["examples"]:
        paths.append(out_dir / e["static"])
        if e.get("motion"):
            paths.append(out_dir / e["motion"])
    for h in roster.get("heroes", []):
        paths.append(out_dir / h["file"])
    paths.append(out_dir / "index.md")
    return paths


def check_drift(seed: int) -> int:
    expected = expected_paths(DEFAULT_OUT)
    missing = [p for p in expected if not p.exists()]
    if missing:
        print("Missing committed screenshots:")
        for p in missing:
            print(f"  - {p.relative_to(ROOT)}")
        print("Run: python tools/screenshots/generate.py")
        return 1

    before = {p.name: file_digest(p) for p in expected}
    with tempfile.TemporaryDirectory() as tmp:
        tmp_out = Path(tmp) / "screenshots"
        generate_all(seed, tmp_out)
        drift = []
        for p in expected:
            new_p = tmp_out / p.name
            if file_digest(new_p) != before[p.name]:
                drift.append(p.relative_to(ROOT))

    if drift:
        print("Screenshot drift detected (fixtures/renderer vs committed docs):")
        for p in drift:
            print(f"  - {p}")
        print("Re-run generate.py and commit, or merge the screenshots PR.")
        return 1
    print("Screenshots OK (no drift).")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if committed images drift")
    parser.add_argument("--seed", type=int, default=SEED)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    if args.check:
        return check_drift(args.seed)
    paths = generate_all(args.seed, args.out)
    print(f"Wrote {len(paths)} files under {args.out}")
    for p in paths:
        try:
            print(f"  {p.relative_to(ROOT)}")
        except ValueError:
            print(f"  {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
